import type { DaySlide, StudioSpec } from "./schema";

// A prepared studio for the bundled basketball clip, built from the manually
// reviewed ball positions in shared/physics.ts (source time − 13.5 s).
const ball: Array<[number, number, number]> = [
  [0.6, 0.415, 0.21],
  [0.7, 0.4815, 0.2063],
  [0.8, 0.537, 0.169],
  [0.9, 0.53, 0.129],
  [1.0, 0.533, 0.1],
  [1.1, 0.533, 0.079],
  [1.2, 0.493, 0.0625],
  [1.3, 0.419, 0.073],
  [1.4, 0.367, 0.094],
  [1.5, 0.356, 0.135],
  [1.6, 0.396, 0.19],
  [1.7, 0.452, 0.256],
  [1.8, 0.593, 0.34],
];

export const SAMPLE_EVENT_ID = "sample-basketball";

export const SAMPLE_STUDIO: StudioSpec = {
  version: "studio-1",
  eventId: SAMPLE_EVENT_ID,
  generatedAt: "2026-09-16T00:00:00.000Z",
  clip: {
    url: "/demo/basketball-event.mp4",
    durationSeconds: 2.3,
    width: 1080,
    height: 1920,
    eventFrom: 0.6,
    eventTo: 1.8,
  },
  headline: {
    title: "At the top of the shot, does gravity take a break?",
    subtitle: "The ball stops rising for an instant. The force pulling it down never stops.",
    concept: "Projectile motion",
    summary:
      "Once the ball leaves the hands, gravity is the only force that matters. It changes vertical velocity the whole flight, while horizontal velocity stays steady.",
    equation: "a_y = −g",
    keyIdeas: [
      "After release, the net force on the ball is its weight, pointing down.",
      "At the top, vertical velocity is zero but acceleration is still g downward.",
      "Mass does not change the path when air resistance is ignored.",
    ],
  },
  annotations: {
    tracks: [
      {
        id: "ball",
        label: "Basketball",
        role: "body",
        samples: ball.map(([t, x, y]) => ({ t, x, y, w: 0.1, h: 0.056, visible: true })),
      },
    ],
    overlays: [
      { id: "halo-ball", type: "halo", from: 0.6, to: 1.85, track: "ball", tone: "focus" },
      { id: "trail-ball", type: "trail", from: 0.6, to: 1.85, track: "ball", style: "comet" },
      {
        id: "vec-velocity",
        type: "vector",
        from: 0.7,
        to: 1.8,
        anchor: { track: "ball" },
        quantity: "velocity",
        direction: { mode: "motion" },
        magnitude: 0.7,
        scale: "speed",
        label: "v",
      },
      {
        id: "vec-weight",
        type: "vector",
        from: 0.75,
        to: 1.85,
        anchor: { track: "ball" },
        quantity: "weight",
        direction: { mode: "angle", deg: 270 },
        magnitude: 0.55,
        scale: "fixed",
        label: "mg",
      },
      {
        id: "label-apex",
        type: "label",
        from: 1.12,
        to: 1.5,
        anchor: { track: "ball" },
        text: "top: v_y = 0",
        tone: "hot",
      },
      { id: "ghosts-ball", type: "ghosts", from: 1.6, to: 2.3, track: "ball", times: [0.8, 1.0, 1.2, 1.4, 1.6] },
    ],
    chapters: [
      { t: 0, title: "Set", caption: "The hands still support the ball. Legs and arms load up the push." },
      { t: 0.6, title: "Release", caption: "Once it leaves the hands, gravity is the only force that matters." },
      { t: 1.15, title: "Apex", caption: "Vertical velocity reaches zero for an instant. Gravity keeps pulling." },
      { t: 1.55, title: "Descent", caption: "The same downward pull now speeds the ball toward the hoop." },
    ],
    freezes: [{ t: 1.2, holdSeconds: 1.8, caption: "Top of the arc: v_y = 0, yet the acceleration is still g, downward." }],
    slowmo: [{ from: 0.95, to: 1.45, rate: 0.45 }],
    focusT: 1.2,
  },
  revealOverlays: [
    {
      id: "reveal-release",
      type: "label",
      from: 0.55,
      to: 0.75,
      anchor: { track: "ball" },
      text: "release: free flight begins",
      tone: "blue",
    },
  ],
  quiz: [
    {
      id: "find-release",
      type: "scrub",
      t: 0.3,
      kicker: "Find the release",
      prompt: "Scrub to the first moment the ball is no longer touching the hands.",
      hint: "Watch the gap between fingertips and ball, frame by frame.",
      explanation:
        "From release on, the hands no longer push. The ball becomes a projectile: only gravity (and a little air) acts on it.",
      reveal: ["reveal-release", "halo-ball"],
      answerT: 0.62,
      toleranceS: 0.22,
    },
    {
      id: "net-force-apex",
      type: "vector",
      t: 1.2,
      kicker: "Draw the force",
      prompt: "Near the top of the arc, draw the direction of the net force on the ball.",
      hint: "What is still pulling on the ball once nothing touches it?",
      explanation:
        "Gravity never takes a break. With air resistance ignored, the net force is the ball's weight, straight down, even at the top.",
      reveal: ["vec-weight"],
      anchor: { track: "ball" },
      quantity: "weight",
      answerDeg: 270,
      toleranceDeg: 30,
    },
    {
      id: "zero-at-apex",
      type: "choice",
      t: 1.2,
      kicker: "What hits zero?",
      prompt: "At the very top of the shot, which quantity is zero in the ideal model?",
      hint: "Split the motion into sideways and up-down parts.",
      explanation:
        "Only vertical velocity is zero at the apex. The ball still moves sideways, and gravity still accelerates it downward.",
      reveal: ["label-apex", "vec-velocity"],
      options: [
        { text: "Horizontal velocity", correct: false, feedback: "The ball keeps drifting toward the hoop; nothing slows its sideways motion." },
        { text: "Vertical velocity", correct: true, feedback: "Right: it switches from rising to falling, so for an instant it is zero." },
        { text: "Acceleration", correct: false, feedback: "A common trap. Acceleration is g downward the whole flight, including the top." },
      ],
    },
    {
      id: "predict-descent",
      type: "path",
      t: 1.3,
      kicker: "Predict the path",
      prompt: "The ball has just passed the top. Which path does it follow next?",
      hint: "Gravity keeps adding downward velocity every instant.",
      explanation:
        "The path keeps curving downward because gravity changes the vertical velocity at a steady rate. (The camera is moving too, so the on-screen curve is not a perfect parabola.)",
      reveal: ["trail-ball"],
      track: "ball",
      horizonS: 0.5,
    },
  ],
  lab: {
    engine: "projectile",
    title: "Shape the shot",
    goal: "Change the launch speed, angle and release height, then watch how time in the air, peak height and distance respond.",
    skin: {
      body: { name: "basketball", shape: "ball", color: "#d9772b" },
      other: null,
      surface: { name: "court", material: "wood" },
      agent: "player",
    },
    params: {
      speed: { value: 7.5, min: 4, max: 12 },
      angle: { value: 52, min: 25, max: 75 },
      height: { value: 2.1, min: 1.5, max: 3 },
      mass: { value: 0.62, min: 0.1, max: 3 },
      radius: { value: 0.12, min: 0.05, max: 0.3 },
      drag: { value: 0, min: 0, max: 1 },
    },
    featured: ["speed", "angle", "height", "drag"],
    readouts: ["maxHeight", "flightTime", "range"],
    experiments: [
      {
        id: "steeper",
        title: "Launch it steeper",
        question: "Same speed, but aimed at 68° instead of 52°. What happens to the highest point?",
        change: { angle: 68 },
        metric: "maxHeight",
        expect: "increase",
        explanation: "More of the launch speed goes into the vertical part, so gravity needs longer to stop the rise and the ball climbs higher.",
      },
      {
        id: "heavier",
        title: "Use a much heavier ball",
        question: "Swap in a 2.5 kg ball with the same launch. How far does it land?",
        change: { mass: 2.5 },
        metric: "range",
        expect: "same",
        explanation: "Without air drag, every mass falls with the same acceleration g, so the path is identical.",
      },
      {
        id: "faster",
        title: "Shoot a little harder",
        question: "Launch at 9 m/s instead of 7.5 m/s. What happens to the time in the air?",
        change: { speed: 9 },
        metric: "flightTime",
        expect: "increase",
        explanation: "A larger vertical launch speed takes gravity longer to reverse, so the ball stays up longer.",
      },
    ],
    challenge: {
      title: "Reach the rim",
      prompt: "The hoop is about 4.2 m away. Adjust one slider so the ball lands 4.2 m out.",
      metric: "range",
      target: 4.2,
      tolerance: 0.15,
      hint: "Speed changes distance the most. Try small steps.",
    },
    takeaway: "Every shot you saw is the same idea: steady sideways motion plus a downward acceleration of g.",
  },
  provenance: {
    kind: "prepared",
    note: "Prepared from twelve manually reviewed ball positions; lab values are hypothetical.",
  },
};

export const SAMPLE_SLIDE: DaySlide = {
  eventId: SAMPLE_EVENT_ID,
  sessionId: "sample",
  subject: "Basketball shot in free flight",
  concept: "gravity acts during the whole flight",
  objectiveIds: ["released-object-motion"],
  kind: "observed_action",
  sourceInterval: { startSeconds: 14.1, endSeconds: 15.3 },
  clip: { url: SAMPLE_STUDIO.clip.url, mimeType: "video/mp4", durationSeconds: 2.3, width: 1080, height: 1920 },
  posterUrl: "/demo/coaching-frame.jpg",
  stage: "ready",
  title: SAMPLE_STUDIO.headline.title,
  engine: "projectile",
  error: null,
};
